.Dd October 1, 2025
.Dt SXWM 1
.Os
.Sh NAME
.Nm sxwm
.Nd simple X11 window manager
.Sh SYNOPSIS
.Nm sxwm
.Op Fl v | Fl -version
.Sh DESCRIPTION
.Nm sxwm
is a minimal, user-friendly tiling window manager for X11.
It is configured through a plain text file and supports
on-the-fly reconfiguration.
.Sh LAUNCH ARGUMENTS
.Bl -tag -width Ds
.It Fl v , Fl -version
Displays the current version of
.Nm sxwm .
.El
.Sh CONFIGURATION
.Nm sxwm
is configured via a simple text file located at
.Pa ~/.config/sxwmrc .
Changes can be applied instantly by reloading the configuration (MOD + r).
.Pp
The file uses a
.Sy key
:
.Sy value
format.
Lines starting with
.Sy #
are ignored.
.Ss General Options
.Bl -column "focused_border_colour" "Integer" "#c0cbff" "Border color for the currently focused window." -offset indent
.It Sy Option Ta Sy Type Ta Sy Default Ta Sy Description
.It mod_key Ta String Ta super Ta Sets the primary modifier key (alt, super, ctrl).
.It gaps Ta Integer Ta 10 Ta Pixels between windows and screen edges.
.It border_width Ta Integer Ta 1 Ta Thickness of window borders in pixels.
.It focused_border_colour Ta Hex Ta #c0cbff Ta Border color for the currently focused window.
.It unfocused_border_colour Ta Hex Ta #555555 Ta Border color for unfocused windows.
.It swap_border_colour Ta Hex Ta #fff4c0 Ta Border color when selecting a window to swap (MOD+Shift+Drag).
.It master_width Ta Integer Ta 60 Ta Percentage of the screen width for the master window.
.It motion_throttle Ta Integer Ta 60 Ta Target FPS for mouse drag actions.
.It resize_master_amount Ta Integer Ta 1 Ta Percent to increase/decrease master width.
.It resize_stack_amount Ta Integer Ta 20 Ta How many pixels to increase/decrease stack windows by.
.It snap_distance Ta Integer Ta 5 Ta Distance (px) before a floating window snaps to edge.
.It move_window_amount Ta Integer Ta 10 Ta Number of pixels to move the window with keyboard.
.It resize_window_amount Ta Integer Ta 10 Ta Number of pixels to resize the window with keyboard.
.It start_fullscreen Ta String Ta \&"st\&" Ta Starts specified windows that should start fullscreened. Enclosed in quotes and comma-seperated.
.It new_win_focus Ta Bool Ta true Ta Whether openening new windows should also set focus to them or keep on current window.
.It warp_cursor Ta Bool Ta true Ta Warp the cursor to the middle of newly focused windows.
.It floating_on_top Ta Bool Ta true Ta Whether floating windows should always draw over tiled ones
.It new_win_master Ta Bool Ta false Ta New windows will open as master window.
.It should_float Ta String Ta \&"st\&" Ta Always-float rule. Multiple entries should be comma-seperated. Optionally, entries can be enclosed in quotes.
.It exec Ta String Ta Nothing Ta Command to run on startup (e.g., sxbar, picom, \&"autostart\&", etc.).
.It can_swallow Ta String Ta st Ta Windows that can swallow.
.It can_be_swallowed Ta String Ta mpv Ta Windows that can be swallowed.
.El
.Sh KEYBINDINGS
.Ss Syntax
Modifiers: mod, shift, ctrl, alt, super ...
.br
Key: Case-insensitive keysym (e.g., Return, q, 1)
.Bd -ragged -offset indent
To find the key do xev | grep "keysym"
and press the key in the box.
.Ed
Action: Either an external command (in quotes) or internal function.
.br
move: Move to that workspace
.br
swap: Swap window to that workspace
.br
_n_: Workspace / Scratchpad number
.br
create: Creates a scratchpad on that slot
.br
toggle: Toggles the visibility of that scratchpad
.br
remove: Removes the scratchpad on that slot
.Pp
Example syntax:
.Bd -literal
bind : modifier + ... + key : action
.Ed
.Bd -literal
scratchpad : modifier + ... + key : create n
scratchpad : modifier + ... + key : toggle n
scratchpad : modifier + ... + key : remove n
.Ed
.Bd -literal
workspace : modifier + ... + key : move n
workspace : modifier + ... + key : swap n
.Ed
.Ss Available Functions
.Bl -column "switch_previous_workspace" "Switch to the previous workspace." -offset indent
.It Sy Function Name Ta Sy Description
.It centre_window Ta Centre the focused window.
.It close_window Ta Closes the focused window.
.It decrease_gaps Ta Shrinks gaps.
.It focus_next Ta Moves focus forward in the stack.
.It focus_prev Ta Moves focus backward in the stack.
.It focus_next_mon Ta Switches focus to the next monitor.
.It focus_prev_mon Ta Switches focus to the previous monitor.
.It fullscreen Ta Fullscreen the focused window.
.It global_floating Ta Toggles floating state for all windows.
.It increase_gaps Ta Expands gaps.
.It master_next Ta Moves focused window down in master/stack order.
.It master_prev Ta Moves focused window up in master/stack order.
.It master_increase Ta Expands master width.
.It master_decrease Ta Shrinks master width.
.It move_next_mon Ta Moves the focused window to the next monitor.
.It move_prev_mon Ta Moves the focused window to the previous monitor.
.It move_win_up Ta Moves the focused window up (keyboard).
.It move_win_down Ta Moves the focused window down (keyboard).
.It move_win_left Ta Moves the focused window left (keyboard).
.It move_win_right Ta Moves the focused window right (keyboard).
.It quit Ta Exits sxwm.
.It reload_config Ta Reloads config.
.It resize_win_up Ta Resizes the focused window up (keyboard).
.It resize_win_down Ta Resizes the focused window down (keyboard).
.It resize_win_left Ta Resizes the focused window left (keyboard).
.It resize_win_right Ta Resizes the focused window right (keyboard).
.It stack_increase Ta Increase the height of the focused stack window.
.It stack_decrease Ta Decrease the height of the focused stack window.
.It switch_previous_workspace Ta Switch to the previous workspace.
.It toggle_floating Ta Toggles floating state of current window.
.It toggle_monocle Ta Toggles monocle layout.
.El
.Ss Example Bindings
.Bd -literal
# Launch terminal
bind : mod + Return : "st"
# Close window
bind : mod + shift + q : close_window

# Scratchpads
scratchpad : mod + ctrl + Return : create 1
scratchpad : mod + shift + b : toggle 2
scratchpad : mod + alt + b : remove 2

# Switch workspace
workspace : mod + 3 : move 3
# Move window to workspace
workspace : mod + shift + 5 : swap 5
.Ed
.Sh DEFAULT KEYBINDINGS
In
.Pa default_sxwmrc
file.
